apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: primetester
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: 4000